[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_2 = "2dpricY6iQ7B5B65SDp5erm8psr1gqeo6Qz96ZDDKt2V"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dotenterprises/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
