[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day3 = "9nZJMqhVh4oHpLgzQJvnwguyy93KkWKyB2rK82RdSr3R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dotenterprises/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
