[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_5 = "JBaKPeGdDnddc1KyopkKxYN8i7Pw7qfkm2kHWQfRSzW4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dotenterprises/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
