[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day2 = "B5CzA4FsgGJC851U6FvrMipayKZ3ogdxsn4apjBAqX8i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dotenterprises/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
